# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 21
# Issues with these labels will never be considered stale
exemptLabels:
  - backlog
  - needs/triage
  - kind/debt
  - kind/requirement
  - kind/bug
  - target/1.5.0
  - target/1.5.2
  - target/1.5.4
  - target/1.5.5
  - target/1.6.0
  - target/1.6.1
  - target/1.6.2
  - target/1.7.0
# Label to use when marking an issue as stale
staleLabel: staled
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
